language: python
dist: xenial  # for python3.7+ testing

python:
- 3.6
- 3.7
- 3.8-dev

install:
# numpy requires some additional dependencies
- sudo apt-get update
- sudo apt-get install libblas-dev liblapack-dev libatlas-base-dev gfortran libhdf5-dev
- pip install -r test/requirements-dev.txt
- find . -name "requirements.txt" -exec pip install -r "{}" \;

script:
# Test that notebooks run successfully
- eval "treon $(awk '{printf " --exclude " $0}' test/ignore)"
# Naive test to check that output committed with notebook-
- find . -name "*.ipynb" | tr '\n' '\0' | xargs -0 -n1 sh test/test_output.sh
