language: python

python:
- 3.7

install:
- pip install -r test/requirements-dev.txt

before_script:
# To ignore a directory, we can just delete the directory
# so that treon doesn't see it.
- xargs -I @ rm -rf @ < test/ignore

script:
- treon